package client

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"slices"
	"strings"
	"unicode"

	"github.com/nats-io/nats.go"
	"github.com/simpleiot/simpleiot/data"
)

// NTPConfigPath points to the systemd-timesyncd configuration file
const NTPConfigPath = "/etc/systemd/timesyncd.conf.d/simpleiot.conf"

// NTPClient is a SimpleIoT client that synchronizes NTP servers to local
// systemd-timesync configuration
type NTPClient struct {
	log      *log.Logger
	nc       *nats.Conn
	config   NTP
	stopCh   chan struct{}
	pointsCh chan NewPoints
}

// NTP client configuration
type NTP struct {
	ID              string   `node:"id"`
	Parent          string   `node:"parent"`
	Servers         []string `point:"server"`
	FallbackServers []string `point:"fallbackServer"`
}

// NewNTPClient returns a new NTPClient using its
// configuration read from the Client Manager
func NewNTPClient(nc *nats.Conn, config NTP) Client {
	// TODO: Ensure only one NTP client exists
	return &NTPClient{
		log:      log.New(os.Stderr, "NTP: ", log.LstdFlags|log.Lmsgprefix),
		nc:       nc,
		config:   config,
		stopCh:   make(chan struct{}),
		pointsCh: make(chan NewPoints),
	}
}

// Run starts the NTP Client
func (c *NTPClient) Run() error {
	c.log.Println("Starting NTP client")
	err := c.UpdateConfig()
	if err != nil {
		c.log.Println("error updating systemd-timesyncd config:", err)
	}
loop:
	for {
		select {
		case <-c.stopCh:
			break loop
		case points := <-c.pointsCh:
			// Update local configuration
			err := data.MergePoints(points.ID, points.Points, &c.config)
			if err != nil {
				return fmt.Errorf("merging points: %w", err)
			}
			err = c.UpdateConfig()
			if err != nil {
				c.log.Println("error updating systemd-timesyncd config:", err)
				break // select
			}
		}
	}
	return nil
}

// ntpServerOK reports whether a server name can be written as one word of
// a timesyncd setting. Whitespace or a control character would let a point
// add a setting of its own to the file.
func ntpServerOK(server string) bool {
	if server == "" {
		return false
	}
	for _, r := range server {
		if unicode.IsSpace(r) || unicode.IsControl(r) {
			return false
		}
	}
	return true
}

// ntpConfig renders the timesyncd drop-in for the configured servers.
// Servers that fail ntpServerOK are left out.
func ntpConfig(servers, fallbackServers []string) []byte {
	var b strings.Builder
	b.WriteString(`
# This file is auto-generated by SimpleIoT
# DO NOT EDIT OR REMOVE!
[Time]
`)
	write := func(key string, servers []string) {
		servers = slices.DeleteFunc(slices.Clone(servers), func(s string) bool {
			return !ntpServerOK(s)
		})
		if len(servers) > 0 {
			b.WriteString(key + "=" + strings.Join(servers, " ") + "\n")
		}
	}
	write("NTP", servers)
	write("FallbackNTP", fallbackServers)
	return []byte(b.String())
}

// UpdateConfig writes the NTP configuration to NTPConfigPath and restarts
// system-timesyncd
func (c *NTPClient) UpdateConfig() error {
	for _, s := range slices.Concat(c.config.Servers, c.config.FallbackServers) {
		if !ntpServerOK(s) {
			c.log.Printf("ignoring NTP server %q", s)
		}
	}
	data := ntpConfig(c.config.Servers, c.config.FallbackServers)

	currData, err := os.ReadFile(NTPConfigPath)
	if err == nil && slices.Equal(currData, data) {
		// No changes to file
		return nil
	}
	err = os.WriteFile(NTPConfigPath, data, 0644)
	if err != nil {
		return err
	}
	// Restart NTP
	return exec.Command("/usr/bin/systemctl", "restart", "systemd-timesyncd").Run()
}

// Stop stops the NTP Client
func (c *NTPClient) Stop(error) {
	close(c.stopCh)
}

// Points is called when the client's node points are updated
func (c *NTPClient) Points(nodeID string, points []data.Point) {
	c.pointsCh <- NewPoints{
		ID:     nodeID,
		Points: points,
	}
}

// EdgePoints is called when the client's node edge points are updated
func (c *NTPClient) EdgePoints(
	_ string, _ string, _ []data.Point,
) {
	// Do nothing
}
