package client

import (
	"strings"
	"testing"
)

func TestNTPServerOK(t *testing.T) {
	for _, test := range []struct {
		server string
		ok     bool
	}{
		{"time.example.com", true},
		{"192.168.1.1", true},
		{"[2001:db8::1]", true},
		{"", false},
		{"time.example.com\nPollIntervalMinSec=1", false},
		{"time.example.com evil.example.com", false},
		{"time.example.com\r", false},
		{"time\x00.example.com", false},
	} {
		if got := ntpServerOK(test.server); got != test.ok {
			t.Errorf("%q: got %v, want %v", test.server, got, test.ok)
		}
	}
}

func TestNTPConfig(t *testing.T) {
	got := string(ntpConfig(
		[]string{"a.example.com", "bad\nRootDistanceMaxSec=1", "b.example.com"},
		[]string{"c.example.com"},
	))

	want := "\n# This file is auto-generated by SimpleIoT\n# DO NOT EDIT OR REMOVE!\n[Time]\n" +
		"NTP=a.example.com b.example.com\nFallbackNTP=c.example.com\n"
	if got != want {
		t.Errorf("got:\n%s\nwant:\n%s", got, want)
	}

	// each setting on its own line, and nothing from the bad entry
	if strings.Contains(got, "RootDistance") {
		t.Error("injected setting reached the file")
	}

	// no servers, no settings
	got = string(ntpConfig(nil, nil))
	if strings.Contains(got, "NTP=") {
		t.Errorf("unexpected setting in %q", got)
	}
}
