version: 2

before:
  hooks:
    - go mod download
    - go generate ./...

changelog:
  disable: true

builds:
  - main: ./cmd/siot/main.go
    id: siot
    binary: siot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - riscv64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: riscv64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: riscv64
archives:
  - name_template: >-
      {{- .ProjectName }}-
      {{- .Tag }}-
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}{{ .Arm }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
      - goos: linux
        format: tar.gz
      - goos: darwin
        format: tar.gz
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md


checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
#env_files:
#github_token: GITHUB_TOKEN
