// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: internal/pb/device.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DeviceCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cmd    string `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *DeviceCmd) Reset() {
	*x = DeviceCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_device_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCmd) ProtoMessage() {}

func (x *DeviceCmd) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_device_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCmd.ProtoReflect.Descriptor instead.
func (*DeviceCmd) Descriptor() ([]byte, []int) {
	return file_internal_pb_device_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceCmd) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceCmd) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *DeviceCmd) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_internal_pb_device_proto protoreflect.FileDescriptor

var file_internal_pb_device_proto_rawDesc = []byte{
	0x0a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x45,
	0x0a, 0x09, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6d, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x69, 0x6f, 0x74, 0x2f, 0x73, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x69, 0x6f, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_device_proto_rawDescOnce sync.Once
	file_internal_pb_device_proto_rawDescData = file_internal_pb_device_proto_rawDesc
)

func file_internal_pb_device_proto_rawDescGZIP() []byte {
	file_internal_pb_device_proto_rawDescOnce.Do(func() {
		file_internal_pb_device_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_device_proto_rawDescData)
	})
	return file_internal_pb_device_proto_rawDescData
}

var file_internal_pb_device_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_pb_device_proto_goTypes = []interface{}{
	(*DeviceCmd)(nil), // 0: pb.DeviceCmd
}
var file_internal_pb_device_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_device_proto_init() }
func file_internal_pb_device_proto_init() {
	if File_internal_pb_device_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_device_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_device_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_device_proto_goTypes,
		DependencyIndexes: file_internal_pb_device_proto_depIdxs,
		MessageInfos:      file_internal_pb_device_proto_msgTypes,
	}.Build()
	File_internal_pb_device_proto = out.File
	file_internal_pb_device_proto_rawDesc = nil
	file_internal_pb_device_proto_goTypes = nil
	file_internal_pb_device_proto_depIdxs = nil
}
