// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: nats-request.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FIXME -- should we move the below to points? Then the
// API would not have to change in the future when we add
// features.
type NatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncludeDel bool   `protobuf:"varint,1,opt,name=includeDel,proto3" json:"includeDel,omitempty"`
	Type       string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *NatsRequest) Reset() {
	*x = NatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nats_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatsRequest) ProtoMessage() {}

func (x *NatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nats_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatsRequest.ProtoReflect.Descriptor instead.
func (*NatsRequest) Descriptor() ([]byte, []int) {
	return file_nats_request_proto_rawDescGZIP(), []int{0}
}

func (x *NatsRequest) GetIncludeDel() bool {
	if x != nil {
		return x.IncludeDel
	}
	return false
}

func (x *NatsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_nats_request_proto protoreflect.FileDescriptor

var file_nats_request_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6e, 0x61, 0x74, 0x73, 0x2d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x41, 0x0a, 0x0b, 0x4e, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x63, 0x6c, 0x75,
	0x64, 0x65, 0x44, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x6e, 0x63,
	0x6c, 0x75, 0x64, 0x65, 0x44, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_nats_request_proto_rawDescOnce sync.Once
	file_nats_request_proto_rawDescData = file_nats_request_proto_rawDesc
)

func file_nats_request_proto_rawDescGZIP() []byte {
	file_nats_request_proto_rawDescOnce.Do(func() {
		file_nats_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_nats_request_proto_rawDescData)
	})
	return file_nats_request_proto_rawDescData
}

var file_nats_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nats_request_proto_goTypes = []interface{}{
	(*NatsRequest)(nil), // 0: pb.NatsRequest
}
var file_nats_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nats_request_proto_init() }
func file_nats_request_proto_init() {
	if File_nats_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nats_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nats_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nats_request_proto_goTypes,
		DependencyIndexes: file_nats_request_proto_depIdxs,
		MessageInfos:      file_nats_request_proto_msgTypes,
	}.Build()
	File_nats_request_proto = out.File
	file_nats_request_proto_rawDesc = nil
	file_nats_request_proto_goTypes = nil
	file_nats_request_proto_depIdxs = nil
}
