load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "point-size_lib",
    srcs = ["main.go"],
    importpath = "github.com/simpleiot/simpleiot/cmd/point-size",
    visibility = ["//visibility:private"],
    deps = [
        "//data",
        "@org_golang_google_protobuf//proto",
    ],
)

go_binary(
    name = "point-size",
    embed = [":point-size_lib"],
    visibility = ["//visibility:public"],
)
